/**
 * bug-intake.test.ts
 *
 * Pins Bug Development Flow Step 1: deterministic, read-only bug intake, one normalized
 * Dev-side bug identity, for QA-originated, external-tracker, production and
 * developer-discovered bugs — at a declared context level (full · partial · insufficient):
 * a verified QA state always wins, and only its absence degrades. No planning artifact is
 * produced at this step.
 *
 * QA fixtures are a real QA repository generated by ono-plugin-qa's own helper
 * (scripts/fixtures/qa-bugs/README.md) — one bug per lifecycle state.
 *
 *   node --no-warnings scripts/bug-intake.test.ts
 */

import { spawnSync } from "child_process";
import { cpSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync, realpathSync, mkdirSync, existsSync } from "fs";
import { createHash } from "crypto";
import { tmpdir } from "os";
import { join, dirname } from "path";
import * as Intake from "./bug-intake.ts";
import { canonical } from "./qa-release-gate.ts";

const HERE = import.meta.dirname ?? __dirname;
const REPO_ROOT = dirname(HERE);
const QA = join(HERE, "fixtures/qa-bugs/acme-qa");
const QA_OLD = join(HERE, "fixtures/qa-repo/acme-qa"); // BUG-27 and BUG-28 share external_ref JIRA-4411

let failures = 0;
function check(name: string, cond: boolean, detail = ""): void {
  if (cond) console.log(`PASS  ${name}`);
  else {
    failures++;
    console.log(`FAIL  ${name}${detail ? `  — ${detail}` : ""}`);
  }
}
const read = (rel: string): string => readFileSync(join(REPO_ROOT, rel), "utf-8");
const sha = (s: string) => `sha256:${createHash("sha256").update(s).digest("hex")}`;
const api = Intake as any;

/** Every file under a directory with its content hash — to prove nothing was written. */
function snapshot(dir: string): string {
  const out: string[] = [];
  const walk = (d: string) => {
    for (const e of readdirSync(d, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p);
      else out.push(`${p.slice(dir.length)}\0${sha(readFileSync(p, "utf-8"))}`);
    }
  };
  walk(dir);
  return out.join("\n");
}

function cli(args: string[], cwd = REPO_ROOT): any {
  const p = spawnSync(process.execPath, ["--no-warnings", join(HERE, "bug-intake.ts"), ...args], { encoding: "utf-8", cwd });
  try {
    return { code: p.status, json: JSON.parse(p.stdout) };
  } catch {
    return { code: p.status, json: null, raw: p.stdout + p.stderr };
  }
}

const L = (ref: string, root = QA) => api.lookupQaBug?.(root, ref);
const N = (input: Record<string, unknown>) => api.normalizeBug?.(input);
const BEFORE = snapshot(QA);
const BEFORE_OLD = snapshot(QA_OLD);

/* ── 1. QA assigned → ready for Dev ───────────────────────────────────── */
{
  const r = L("BUG-43");
  check("1 assigned bug is ready_for_dev", r?.status === "ready_for_dev" && r.dev_may_start === true, JSON.stringify(r?.status));
  check("1 identity: work_type bug, QA id, origin qa-standalone",
    r?.identity?.work_type === "bug" && r.identity.qa_bug_id === "BUG-43" && r.identity.origin === "qa-standalone");
  check("1 identity: found_in_build is QA's derived value (first reproduction)", r?.identity?.found_in_build === "and-201");
  check("1 identity: affected surfaces", JSON.stringify(r?.identity?.surfaces) === '["android"]');
  check("1 evidence: title, steps, expected, actual, severity",
    r?.evidence?.title === "Checkout total ignores coupon" && r.evidence.steps.length === 3 &&
      r.evidence.expected === "Total shows the 10% discount" && r.evidence.actual === "Total shows the full price" && r.evidence.severity === "major");
  check("1 related QA scopes are carried", JSON.stringify(r?.evidence?.related_scopes) === '["feature:checkout"]');
  check("1 related_feature is the Dev feature QA bound to the related feature scope (dev_handoff)", r?.identity?.related_feature === "checkout-coupons", JSON.stringify(r?.identity?.related_feature));
  check("1 reproduction history is exposed", r?.qa?.reproductions?.length === 1 && r.qa.reproductions[0].outcome === "reproduced");
  check("1 not reopened, so no reopened evidence", r?.reopened === null);
}

/* ── 2. QA reopened → reopened, with the failed cycle's evidence ──────── */
{
  const r = L("qa=BUG-44");
  check("2 reopened bug is reopened and Dev may start the next cycle", r?.status === "reopened" && r.dev_may_start === true, JSON.stringify(r?.status));
  check("2 failed fix build", r?.reopened?.failed_fix_build === "atv-202", JSON.stringify(r?.reopened));
  check("2 failed surfaces", JSON.stringify(r?.reopened?.failed_surfaces) === '["android-tv"]');
  check("2 latest re-test result and notes",
    r?.reopened?.latest_retest?.outcome === "fail" && r.reopened.latest_retest.notes === "Still frozen after resume from Home" && r.reopened.latest_retest.build === "atv-202");
  check("2 re-test evidence", JSON.stringify(r?.reopened?.evidence) === '["videos/BUG-44-atv-202.mp4"]');
  check("2 previous fix claims with outcomes", JSON.stringify(r?.reopened?.previous_fix_claims) === '[{"build":"atv-202","outcome":"failed"}]');
  check("2 no cycle is created at intake", !("cycle" in (r ?? {})) && !("fix_cycle" in (r?.identity ?? {})));
}

/* ── 3–5. QA does not yet, or no longer, hand the bug to Dev ──────────── */
{
  const n = L("BUG-41");
  check("3 new bug needs QA verification; Dev must not start", n?.status === "needs_qa_verification" && n.dev_may_start === false && /verify-bug/.test(n.reason));
  const b = L("BUG-42");
  check("4 verification_blocked needs QA verification; Dev must not start", b?.status === "needs_qa_verification" && b.dev_may_start === false && b.qa.state === "verification_blocked");
  const c = L("BUG-45");
  check("5 closed_verified is closed; Dev must not start", c?.status === "closed" && c.dev_may_start === false && c.qa.state === "closed_verified");
  const f = L("BUG-46");
  check("5 fix_delivered awaits QA re-test; no new fix cycle", f?.status === "awaiting_qa_retest" && f.dev_may_start === false && f.qa.fix_under_test === "and-202");
  for (const r of [n, b, c, f]) check(`3–5 ${r?.identity?.qa_bug_id}: QA ownership is never overridden — the reason names QA's next action`, typeof r?.reason === "string" && r.reason.length > 20);
}

/* ── 6. external_ref on a QA bug; lookups by external ref ─────────────── */
{
  const r = L("BUG-43");
  check("6 a QA bug carries its external_ref", r?.identity?.external_ref === "PAY-1182");
  check("6 its bug_key is still the QA id", r?.identity?.bug_key === "BUG-43");
  check("6 lookup by external ref finds the QA bug", L("external=PAY-1182")?.identity?.qa_bug_id === "BUG-43");
  check("6 qa + external must identify the same bug", L("qa=BUG-43,external=PAY-1182")?.status === "ready_for_dev" && L("qa=BUG-44,external=PAY-1182")?.status === "invalid");
  const amb = L("external=JIRA-4411", QA_OLD);
  check("6 an external ref shared by two QA bugs is ambiguous", amb?.status === "ambiguous" && JSON.stringify(amb.candidates) === '["BUG-27","BUG-28"]', JSON.stringify(amb));
  check("6 an unknown QA bug is invalid, not guessed", L("BUG-99")?.status === "invalid" && L("external=NOPE-1")?.status === "invalid");
}

/* ── 7–10. external, dev-review, dev-testing, production ──────────────── */
const EVIDENCE = { title: "Checkout total ignores coupon", steps: ["Add an item to the cart", "Apply coupon SAVE10", "Open checkout"], expected: "Total shows the 10% discount", actual: "Total shows the full price" };
{
  const e = N({ origin: "external", external_ref: "PAY-1182", ...EVIDENCE, environment: "Pixel 8, staging", surfaces: ["android"] });
  check("7 external-only bug is ready_for_dev without a QA id", e?.status === "ready_for_dev" && e.identity.qa_bug_id === null && e.identity.external_ref === "PAY-1182");
  check("7 environment is carried", e?.evidence?.environment === "Pixel 8, staging");
  for (const origin of ["dev-review", "dev-testing", "production"]) {
    const d = N({ origin, ...EVIDENCE, related_feature: "checkout" });
    check(`${origin === "dev-review" ? 8 : origin === "dev-testing" ? 9 : 10} ${origin} bug is ready_for_dev with a generated DEV key`,
      d?.status === "ready_for_dev" && /^DEV-[0-9a-f]{8}$/.test(d.identity.bug_key) && d.identity.origin === origin, JSON.stringify(d?.identity));
    check(`${origin} bug keeps a given related feature, and needs no QA scope`, d?.identity?.related_feature === "checkout" && d.qa === null);
  }
  check("10 an unknown origin is invalid", N({ origin: "rumour", ...EVIDENCE })?.status === "invalid");
  check("7 an external origin requires an external ref", N({ origin: "external", ...EVIDENCE })?.status === "invalid");
}

/* ── 11–13. deterministic bug_key ─────────────────────────────────────── */
{
  check("11 bug_key from the QA id", L("BUG-44")?.identity?.bug_key === "BUG-44");
  check("12 bug_key from external_ref", N({ origin: "external", external_ref: "PAY-77", ...EVIDENCE })?.identity?.bug_key === "PAY-77");
  const expected = `DEV-${createHash("sha256").update(["production", EVIDENCE.title, EVIDENCE.steps[0]].join("\n")).digest("hex").slice(0, 8)}`;
  const a = N({ origin: "production", ...EVIDENCE });
  const b = N({ origin: "production", ...EVIDENCE, actual: "different actual, same key inputs" });
  check("13 generated DEV key is sha256(origin, title, first step) — first 8 hex", a?.identity?.bug_key === expected, `${a?.identity?.bug_key} vs ${expected}`);
  check("13 it is stable across calls and ignores fields outside the key", a?.identity?.bug_key === b?.identity?.bug_key);
  check("13 a different origin, title or first step gives a different key",
    N({ origin: "dev-review", ...EVIDENCE })?.identity?.bug_key !== expected &&
      N({ origin: "production", ...EVIDENCE, title: "Other" })?.identity?.bug_key !== expected &&
      N({ origin: "production", ...EVIDENCE, steps: ["Other first step", ...EVIDENCE.steps.slice(1)] })?.identity?.bug_key !== expected);
}

/* ── 14–18. evidence fingerprint ──────────────────────────────────────── */
{
  const base = { ...EVIDENCE, surfaces: ["android"], found_in_build: "and-201" };
  const fp = (e: Record<string, unknown>) => api.evidenceFingerprint?.(e);
  check("14 same evidence, same fingerprint", typeof fp(base) === "string" && fp(base) === fp({ ...base }) && /^sha256:[0-9a-f]{64}$/.test(fp(base)));
  check("14 a QA bug and the same evidence entered externally fingerprint identically",
    L("BUG-43")?.bug_evidence_fingerprint === N({ origin: "external", external_ref: "PAY-1182", ...base })?.bug_evidence_fingerprint);
  check("14 surface order does not matter", fp({ ...base, surfaces: ["b", "a"] }) === fp({ ...base, surfaces: ["a", "b"] }));
  check("15 QA state, fix history, re-test history and timestamps never enter the fingerprint",
    fp({ ...base, state: "reopened", fix_claims: [1], retests: [1], at: "2026-10-05T10:00:00Z", severity: "critical", description: "x", external_ref: "Z" }) === fp(base));
  const r44 = L("BUG-44");
  check("15 a reopened QA bug's fingerprint equals that of its bare evidence",
    r44?.bug_evidence_fingerprint === fp({ title: r44?.evidence?.title, steps: r44?.evidence?.steps, expected: r44?.evidence?.expected, actual: r44?.evidence?.actual, surfaces: r44?.identity?.surfaces, found_in_build: r44?.identity?.found_in_build }));
  check("16 steps change it", fp({ ...base, steps: [...EVIDENCE.steps, "Pay"] }) !== fp(base));
  check("16 expected changes it", fp({ ...base, expected: "x" }) !== fp(base));
  check("16 actual changes it", fp({ ...base, actual: "x" }) !== fp(base));
  check("16 title changes it", fp({ ...base, title: "x" }) !== fp(base));
  check("17 a surface change changes it", fp({ ...base, surfaces: ["android", "ios"] }) !== fp(base));
  check("18 found_in_build changes it", fp({ ...base, found_in_build: "and-202" }) !== fp(base) && fp({ ...base, found_in_build: null }) !== fp(base));
}

/* ── 19–20. unsafe identity and missing evidence ──────────────────────── */
{
  for (const bad of ["../etc", "PAY/1", "https://jira.example.com/PAY-1", ".", "..", "a b", "x".repeat(80), ""]) {
    const r = N({ origin: "external", external_ref: bad, ...EVIDENCE });
    check(`19 unsafe external ref ${JSON.stringify(bad.slice(0, 20))} is rejected`, r?.status === "invalid" && /UNSAFE_IDENTITY|MISSING/.test(r.code ?? ""), JSON.stringify(r?.code));
  }
  check("19 an unsafe QA id is rejected before any file is read", L("../../etc")?.status === "invalid" && L("../../etc")?.code === "UNSAFE_IDENTITY");
  for (const missing of ["title", "steps", "expected", "actual"]) {
    const input: Record<string, unknown> = { origin: "production", ...EVIDENCE };
    if (missing === "steps") input.steps = [];
    else delete input[missing];
    const r = N(input);
    check(`20 missing ${missing} is rejected`, r?.status === "invalid" && r.code === "MISSING_EVIDENCE" && r.missing?.includes(missing), JSON.stringify(r));
  }
}

/* ── reopened after more than one failed fix ──────────────────────────── */
{
  // The next cycle starts from the most recent failed fix, never the first one.
  const view = api.parseBugView(readFileSync(join(QA, "bugs/BUG-44/bug.md"), "utf-8"), "BUG-44");
  view.fixClaims.push({ Build: "atv-204", "Claimed at": "2026-10-06T09:00:00.000Z", Outcome: "failed" });
  view.retests.push({ Run: "retest-x", Build: "atv-204", "Fix build": "atv-204", Surface: "android-tv", Device: "Chromecast", Outcome: "fail", At: "2026-10-06T09:30:00.000Z", Notes: "Frozen on cold resume" });
  const runs = [[{ kind: "run.opened", run_id: "retest-x" }, { kind: "result.recorded", case_key: "bug:BUG-44#R1", evidence: ["videos/BUG-44-atv-204.mp4"] }]];
  const r = api.reopenedEvidence(view, runs, "bug:BUG-44");
  check("2 two failed fixes: the latest failed fix build is the one carried", r?.failed_fix_build === "atv-204" && r.latest_retest.notes === "Frozen on cold resume", JSON.stringify(r?.failed_fix_build));
  check("2 two failed fixes: evidence is the latest re-test's, every claim is kept", JSON.stringify(r?.evidence) === '["videos/BUG-44-atv-204.mp4"]' &&
    JSON.stringify(r.previous_fix_claims) === '[{"build":"atv-202","outcome":"failed"},{"build":"atv-204","outcome":"failed"}]');
}

/* ── context levels: full · partial · insufficient ────────────────────── */
const proceeds = (r: any) => r?.dev_may_start === true;
const codes = (r: any): string[] => (r?.warnings ?? []).map((w: any) => w.code);
{
  // C1–C4 — full QA context: a verified QA state decides, exactly as before.
  const a = L("BUG-43"), ro = L("BUG-44"), n = L("BUG-41"), cv = L("BUG-45");
  check("C1 full context, assigned → proceed", a?.context_level === "full" && proceeds(a) && a.status === "ready_for_dev" && a.qa_state === "assigned" && a.qa_state_verified === true && a.warnings?.length === 0, JSON.stringify([a?.context_level, a?.qa_state, a?.warnings]));
  check("C2 full context, reopened → proceed", ro?.context_level === "full" && proceeds(ro) && ro.status === "reopened" && ro.qa_state === "reopened" && ro.qa_state_verified === true);
  check("C3 full context, new → block", n?.context_level === "full" && !proceeds(n) && n.status === "needs_qa_verification" && n.qa_state === "new" && n.qa_state_verified === true);
  check("C4 full context, closed_verified → block", cv?.context_level === "full" && !proceeds(cv) && cv.status === "closed" && cv.qa_state === "closed_verified");
  check("C full context records both sources",
    a?.provenance?.evidence?.source === "qa-ledger" && a.provenance.evidence.path === "qa-ledger/scopes/bug/BUG-43.jsonl" && a.provenance.evidence.verification === "hash-chain" &&
      a.provenance.state?.source === "qa-bug-view" && a.provenance.state.path === "bugs/BUG-43/bug.md");
  for (const id of ["BUG-41", "BUG-42", "BUG-45", "BUG-46"]) {
    const r = L(id);
    check(`C14 verified QA denial on ${id} (${r?.qa_state}) blocks in full context`, r?.context_level === "full" && r.qa_state_verified === true && !proceeds(r));
  }
}
{
  const tmp = realpathSync(mkdtempSync(join(tmpdir(), "bug-intake-")));
  const copy = join(tmp, "acme-qa");
  cpSync(QA, copy, { recursive: true });
  const md = (id: string) => join(copy, `bugs/${id}/bug.md`);
  const edit = (id: string, f: (s: string) => string) => writeFileSync(md(id), f(readFileSync(md(id), "utf-8")));
  const restore = (id: string) => cpSync(join(QA, `bugs/${id}/bug.md`), md(id));
  const partial = (r: any) => r?.context_level === "partial" && r.status === "ready_for_dev" && proceeds(r) && r.qa_state === null && r.qa_state_verified === false &&
    r.qa === null && r.reopened === null && codes(r).includes("QA_STATE_UNAVAILABLE");
  const show = (r: any) => JSON.stringify([r?.context_level, r?.status, r?.code, codes(r)]);
  const invented = (r: any) => /\b(assigned|reopened)\b/.test(JSON.stringify([r?.status, r?.qa_state, r?.qa, r?.reason])) || r?.reopened !== null;
  const partials: any[] = [];

  // C5 — no bug.md, but the hash-verified ledger evidence is sufficient.
  rmSync(md("BUG-43"));
  const gone = L("BUG-43", copy);
  partials.push(gone);
  check("C5 missing bug.md, sufficient ledger evidence → partial, proceed", partial(gone) && codes(gone).includes("QA_VIEW_MISSING"), show(gone));
  check("C5 the warning carries QA's regeneration command", gone?.warnings?.some((w: any) => w.code === "QA_VIEW_MISSING" && /bug render --bug bug:BUG-43/.test(w.message)));
  check("C5 partial records its evidence source and no state source",
    gone?.provenance?.evidence?.source === "qa-ledger" && gone.provenance.evidence.path === "qa-ledger/scopes/bug/BUG-43.jsonl" && gone.provenance.evidence.verification === "hash-chain" && gone.provenance.state === null);
  check("C5 partial warnings are deterministic", JSON.stringify(L("BUG-43", copy)?.warnings) === JSON.stringify(gone?.warnings));
  check("C9 partial keeps qa_bug_id, external_ref, bug_key and related_feature",
    gone?.identity?.qa_bug_id === "BUG-43" && gone.identity.external_ref === "PAY-1182" && gone.identity.bug_key === "BUG-43" && gone.identity.related_feature === "checkout-coupons" && gone.identity.origin === "qa-standalone");
  check("C9 partial evidence is the recorded report", gone?.evidence?.actual === "Total shows the full price" && gone.evidence.steps.length === 3 && JSON.stringify(gone.identity.surfaces) === '["android"]');
  check("C partial: a found_in_build QA only derived (not recorded) is unknown — and said so",
    gone?.identity?.found_in_build === null && codes(gone).includes("FOUND_IN_BUILD_UNKNOWN") && /^sha256:[0-9a-f]{64}$/.test(gone.bug_evidence_fingerprint ?? ""));
  check("C partial: the CLI degrades the same way", cli(["lookup", "BUG-43", "--qa-repo", copy]).json?.context_level === "partial");
  restore("BUG-43");

  // C6 — bug.md present but not in the contracted shape.
  writeFileSync(md("BUG-43"), "# not the contracted view\n");
  const garbled = L("BUG-43", copy);
  partials.push(garbled);
  check("C6 unparseable bug.md, sufficient evidence → partial, proceed", partial(garbled) && codes(garbled).includes("QA_VIEW_CONTRACT"), show(garbled));
  restore("BUG-43");
  edit("BUG-43", (s) => s.replace("## Re-test History", "## Retests"));
  const renamed = L("BUG-43", copy);
  partials.push(renamed);
  check("C6 a renamed section → partial", partial(renamed) && codes(renamed).includes("QA_VIEW_CONTRACT"), show(renamed));
  restore("BUG-43");
  edit("BUG-43", (s) => s.replace("## Devices", "## @@").replace("## Linked Test Cases", "## Devices").replace("## @@", "## Linked Test Cases"));
  const reordered = L("BUG-43", copy);
  check("C6 reordered sections → partial", partial(reordered) && codes(reordered).includes("QA_VIEW_CONTRACT"), show(reordered));
  restore("BUG-43");

  // C7 — the state portion cannot be verified without replaying QA's derivation.
  edit("BUG-43", (s) => s.replace("| State | assigned |", "| State | triaged |"));
  const unknown = L("BUG-43", copy);
  partials.push(unknown);
  check("C7 a state the contract does not know → partial, never interpreted", partial(unknown) && codes(unknown).includes("QA_VIEW_CONTRACT"), show(unknown));
  restore("BUG-43");
  edit("BUG-44", (s) => s.replace(/\| retest-[^\n]*\n/, ""));
  const staleRuns = L("BUG-44", copy);
  partials.push(staleRuns);
  check("C7 a view whose history disagrees with the ledger → partial", partial(staleRuns) && codes(staleRuns).includes("QA_VIEW_STALE"), show(staleRuns));
  restore("BUG-44");
  edit("BUG-43", (s) => s.replace("Total shows the full price", "Total shows a wrong price"));
  const staleEvidence = L("BUG-43", copy);
  partials.push(staleEvidence);
  check("C7 a view whose evidence disagrees → partial, evidence from the verified ledger",
    partial(staleEvidence) && codes(staleEvidence).includes("QA_VIEW_STALE") && staleEvidence.evidence.actual === "Total shows the full price", show(staleEvidence));
  restore("BUG-43");
  const run = join(copy, "qa-ledger/runs/retest-20261005T101700Z-c555166e.jsonl");
  writeFileSync(run, readFileSync(run, "utf-8").replace("Still frozen after resume from Home", "Fine now"));
  const tamperedRun = L("BUG-44", copy);
  partials.push(tamperedRun);
  check("C7 a run record that no longer verifies → state unverifiable → partial", partial(tamperedRun) && codes(tamperedRun).includes("QA_LEDGER_UNVERIFIABLE"), show(tamperedRun));
  cpSync(join(QA, "qa-ledger/runs/retest-20261005T101700Z-c555166e.jsonl"), run);

  // C8 — partial context never invents a QA state, not even for a bug QA has reopened.
  rmSync(md("BUG-44"));
  const reopenedGone = L("BUG-44", copy);
  partials.push(reopenedGone);
  check("C8 a reopened bug without its view is partial — not reopened, no fix-cycle evidence", partial(reopenedGone) && reopenedGone.status !== "reopened", show(reopenedGone));
  restore("BUG-44");
  partials.forEach((r, i) => check(`C8 partial result #${i + 1} never labels the bug assigned or reopened`, r !== undefined && !invented(r)));

  // C10 — the same evidence fingerprints identically in full and partial context.
  const full47 = L("BUG-47");
  rmSync(md("BUG-47"));
  const part47 = L("BUG-47", copy);
  check("C10 full and partial context give the same fingerprint for the same evidence",
    full47?.context_level === "full" && part47?.context_level === "partial" && full47.identity.found_in_build === "and-201" && part47.identity.found_in_build === "and-201" &&
      typeof full47.bug_evidence_fingerprint === "string" && full47.bug_evidence_fingerprint === part47.bug_evidence_fingerprint && !codes(part47).includes("FOUND_IN_BUILD_UNKNOWN"),
    JSON.stringify([full47?.bug_evidence_fingerprint, part47?.bug_evidence_fingerprint]));
  check("C10 …and the same identity", JSON.stringify(full47?.identity) === JSON.stringify(part47?.identity));
  restore("BUG-47");

  // C14 — a QA denial the ledger itself records (a resolution) is verified without the view, and wins.
  const resolved = L("BUG-48");
  check("C14 a resolved bug is closed in full context", resolved?.context_level === "full" && resolved.status === "closed" && !proceeds(resolved) && resolved.qa_state === "closed_wont_fix");
  rmSync(md("BUG-48"));
  const resolvedGone = L("BUG-48", copy);
  check("C14 resolved bug without its view: the ledger's resolution is a verified denial — still blocked, never partial",
    resolvedGone?.context_level === "full" && resolvedGone.status === "closed" && !proceeds(resolvedGone) && resolvedGone.qa_state === "closed_wont_fix" && resolvedGone.qa_state_verified === true &&
      resolvedGone.provenance?.state?.source === "qa-ledger" && resolvedGone.provenance.state.record === "bug.resolved", show(resolvedGone));
  restore("BUG-48");
  edit("BUG-48", (s) => s.replace("| State | closed_wont_fix |", "| State | assigned |"));
  const resolvedLying = L("BUG-48", copy);
  check("C14 a view claiming assigned cannot reopen a bug the ledger records as resolved", resolvedLying?.status === "closed" && !proceeds(resolvedLying) && resolvedLying.qa_state === "closed_wont_fix", show(resolvedLying));
  restore("BUG-48");

  // Insufficient — a verified QA record that lacks the evidence Dev needs (QA's helper requires
  // it today; a hash-valid record without it must still never be worked from).
  const s43 = join(copy, "qa-ledger/scopes/bug/BUG-43.jsonl");
  const [created, reported] = readFileSync(s43, "utf-8").trim().split("\n").map((l) => JSON.parse(l));
  const { hash: _h, ...body } = { ...reported, expected: "", actual: "" };
  writeFileSync(s43, `${JSON.stringify(created)}\n${JSON.stringify({ ...body, hash: sha(canonical(body)) })}\n`);
  const thinPartial = L("BUG-43", copy);
  check("C13 verified QA record without expected/actual, no usable view → insufficient", thinPartial?.context_level === "insufficient" && !proceeds(thinPartial) && JSON.stringify(thinPartial.missing) === '["expected","actual"]', show(thinPartial));
  edit("BUG-43", (s) => s.replace("**Expected:** Total shows the 10% discount", "**Expected:** ").replace("**Actual:** Total shows the full price", "**Actual:** "));
  const thinFull = L("BUG-43", copy);
  check("C13 …and with QA's verified assigned state, still insufficient", thinFull?.context_level === "insufficient" && !proceeds(thinFull) && JSON.stringify(thinFull.missing) === '["expected","actual"]', show(thinFull));
  cpSync(join(QA, "qa-ledger/scopes/bug/BUG-43.jsonl"), s43);
  restore("BUG-43");
  // …but a verified QA denial is reported as QA's decision, before any evidence verdict.
  const s41 = join(copy, "qa-ledger/scopes/bug/BUG-41.jsonl");
  const [c41, r41] = readFileSync(s41, "utf-8").trim().split("\n").map((l) => JSON.parse(l));
  const { hash: _h41, ...b41 } = { ...r41, expected: "", actual: "" };
  writeFileSync(s41, `${JSON.stringify(c41)}\n${JSON.stringify({ ...b41, hash: sha(canonical(b41)) })}\n`);
  edit("BUG-41", (s) => s.replace(/^\*\*Expected:\*\* .*$/m, "**Expected:** ").replace(/^\*\*Actual:\*\* .*$/m, "**Actual:** "));
  const thinNew = L("BUG-41", copy);
  check("C14 verified denial (new) with thin evidence: QA's denial is what is reported", thinNew?.context_level === "full" && thinNew.status === "needs_qa_verification" && thinNew.qa_state === "new" && !proceeds(thinNew), show(thinNew));
  cpSync(join(QA, "qa-ledger/scopes/bug/BUG-41.jsonl"), s41);
  restore("BUG-41");

  // Insufficient — no usable, reliable report source.
  const stream = join(copy, "qa-ledger/scopes/bug/BUG-43.jsonl");
  writeFileSync(stream, readFileSync(stream, "utf-8").replace('"Total shows the full price"', '"Total shows nothing"'));
  const tampered = L("BUG-43", copy);
  check("C a hand-edited bug record is unreliable evidence → insufficient, blocked",
    tampered?.context_level === "insufficient" && tampered.status === "invalid" && !proceeds(tampered) && tampered.code === "QA_LEDGER_UNVERIFIABLE" && JSON.stringify(tampered.missing) === '["report_source"]', show(tampered));
  cpSync(join(QA, "qa-ledger/scopes/bug/BUG-43.jsonl"), stream);
  const notQa = L("BUG-43", tmp);
  check("C a path that is not a QA repository → insufficient", notQa?.context_level === "insufficient" && notQa.code === "NOT_A_QA_REPO" && !proceeds(notQa));
  const unknownBug = L("BUG-99", copy);
  check("C an unknown QA bug → insufficient", unknownBug?.context_level === "insufficient" && unknownBug.code === "UNKNOWN_BUG" && !proceeds(unknownBug));
  check("C validate reports degraded for partial context", (rmSync(md("BUG-43")), cli(["validate", "BUG-43", "--qa-repo", copy]).json?.status) === "degraded");
  rmSync(tmp, { recursive: true, force: true });
}
{
  // C11–C13 — insufficient evidence blocks and names exactly what is missing.
  const without = (...keys: string[]) => {
    const input: Record<string, unknown> = { origin: "production", ...EVIDENCE };
    for (const k of keys) k === "steps" ? (input.steps = []) : delete input[k];
    return N(input);
  };
  const t = without("title"), st = without("steps"), ea = without("expected", "actual"), e = without("expected");
  check("C11 missing title → insufficient", t?.context_level === "insufficient" && !proceeds(t) && JSON.stringify(t.missing) === '["title"]', JSON.stringify(t));
  check("C12 missing reproduction steps → insufficient", st?.context_level === "insufficient" && !proceeds(st) && JSON.stringify(st.missing) === '["steps"]');
  check("C13 missing expected and actual → insufficient, both named", ea?.context_level === "insufficient" && JSON.stringify(ea.missing) === '["expected","actual"]');
  check("C13 missing expected alone → insufficient", e?.context_level === "insufficient" && JSON.stringify(e.missing) === '["expected"]');
  const whitespace = N({ origin: "dev-testing", ...EVIDENCE, title: "   " });
  check("C11 a blank title is missing, not present", whitespace?.context_level === "insufficient" && JSON.stringify(whitespace.missing) === '["title"]');
  const ok = N({ origin: "production", ...EVIDENCE });
  check("C a complete non-QA report is full context — QA ownership does not apply, none is claimed",
    ok?.context_level === "full" && proceeds(ok) && ok.qa_state === null && ok.qa_state_verified === false && ok.warnings?.length === 0 &&
      ok.provenance?.evidence?.source === "input" && ok.provenance.state === null);
  check("C surfaces and found_in_build may be unknown", ok?.identity?.surfaces?.length === 0 && ok.identity.found_in_build === null && /^sha256:/.test(ok.bug_evidence_fingerprint));
}

/* ── QA consumer contract ─────────────────────────────────────────────── */
{
  const contract = read("docs/qa-bug-view-contract.md");
  check("QA the consumer contract exists and names both sources", /qa-ledger\/scopes\/bug/.test(contract) && /bugs\/<id>\/bug\.md/.test(contract));
  check("QA the contract pins the QA renderer it was written against", /renderBugMarkdown/.test(contract) && /8d8ed99/.test(contract));
  check("QA the contract states the limitation of reading a derived view", /limitation/i.test(contract));
  const PIN = "sha256:545c77650033c3cb9883b68a73ea9dcbb18acad6754764a0e9a5398dc6c15c23";
  check("QA the contract copy is pinned", sha(contract) === PIN, sha(contract));
}

/* ── CLI ──────────────────────────────────────────────────────────────── */
{
  const a = cli(["lookup", "BUG-44", "--qa-repo", QA]);
  check("CLI lookup prints one JSON object and exits 0", a.code === 0 && a.json?.status === "reopened");
  const v = cli(["validate", "BUG-43", "--qa-repo", QA]);
  check("CLI validate reports the contract and integrity verdict", v.code === 0 && v.json?.status === "valid", JSON.stringify(v.json));
  const n = cli(["normalize", "--origin", "external", "--external", "PAY-1182", "--title", EVIDENCE.title, "--step", EVIDENCE.steps[0], "--step", EVIDENCE.steps[1], "--step", EVIDENCE.steps[2],
    "--expected", EVIDENCE.expected, "--actual", EVIDENCE.actual, "--surfaces", "android", "--found-in-build", "and-201"]);
  check("CLI normalize from flags matches the QA bug's fingerprint", n.json?.bug_evidence_fingerprint === L("BUG-43")?.bug_evidence_fingerprint, JSON.stringify(n.json?.status));
  const tmp = realpathSync(mkdtempSync(join(tmpdir(), "bug-intake-report-")));
  writeFileSync(join(tmp, "report.json"), JSON.stringify({ title: EVIDENCE.title, steps: EVIDENCE.steps, expected: EVIDENCE.expected, actual: EVIDENCE.actual, environment: "prod, v2.4.0" }));
  const rep = cli(["normalize", "--origin", "production", "--report", join(tmp, "report.json")], tmp);
  check("CLI normalize from a report file works", rep.json?.status === "ready_for_dev" && rep.json.evidence.environment === "prod, v2.4.0");
  check("CLI the report file is recorded as the evidence source", rep.json?.provenance?.evidence?.source === "report-file" && rep.json.provenance.evidence.path === join(tmp, "report.json"));
  check("CLI flags are recorded as the evidence source", n.json?.provenance?.evidence?.source === "cli-flags");
  check("24 no planning artifact or any file is generated", readdirSync(tmp).join(",") === "report.json");
  const bad = cli(["frobnicate"]);
  check("CLI an unknown command is a JSON refusal, still exit 0", bad.code === 0 && bad.json?.status === "invalid");
  rmSync(tmp, { recursive: true, force: true });
}

/* ── 21–25. read-only, no Project Knowledge, no QA writes, no planning ── */
{
  check("21 the QA fixture repository is byte-identical after every lookup", snapshot(QA) === BEFORE && snapshot(QA_OLD) === BEFORE_OLD);
  const src = read("scripts/bug-intake.ts").replace(/\/\*\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
  check("21 the helper uses no write API", !/\b(writeFile|appendFile|mkdir|rmSync|rm\(|unlink|rename|copyFile|cpSync|createWriteStream|truncate)/.test(src));
  check("22 the helper never touches Project Knowledge", !/repo-knowledge|\.ono\b|read-repo-knowledge|knowledge lookup/.test(src));
  check("23 the helper never runs the QA helper or any process", !/qa-ledger\.mjs|child_process|spawn|exec(File)?Sync/.test(src));
  check("24 the helper writes no planning artifact path", !/docs\/bugs|bug-work-plan|task-state\.ts|docs\/tasks/.test(src));
  check("the helper reads no clock and no randomness", !/\bnew Date\b|Date\.now|Math\.random|randomUUID/.test(src));
  check("25 the suite is registered with the check harness", /"bug-intake"/.test(read("scripts/check.ts")));
  // /implement-task reads intake through its bug gate since Step 5 (scripts/bug-implementation.ts).
  for (const rel of ["commands/analyze-feature.md", "commands/create-dev-qa-notes.md", "commands/review-code.md", "commands/prepare-mobile-release.md", "scripts/task-state.ts", "scripts/read-repo-knowledge.ts"]) {
    check(`25 ${rel} does not reference bug intake (Step 1 changes nothing downstream)`, !/bug-intake/.test(read(rel)));
  }
}

if (failures > 0) {
  console.log(`\n${failures} failure(s)`);
  process.exit(1);
}
console.log("\nall bug-intake checks passed");
