/**
 * bug-intake.test.ts
 *
 * Pins Bug Development Flow Step 1: deterministic, read-only bug intake and one normalized
 * Dev-side bug identity, for QA-originated, external-tracker, production and
 * developer-discovered bugs. No planning artifact is produced at this step.
 *
 * QA fixtures are a real QA repository generated by ono-plugin-qa's own helper
 * (scripts/fixtures/qa-bugs/README.md) — one bug per lifecycle state.
 *
 *   node --no-warnings scripts/bug-intake.test.ts
 */

import { spawnSync } from "child_process";
import { cpSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync, realpathSync, mkdirSync, existsSync } from "fs";
import { createHash } from "crypto";
import { tmpdir } from "os";
import { join, dirname } from "path";
import * as Intake from "./bug-intake.ts";

const HERE = import.meta.dirname ?? __dirname;
const REPO_ROOT = dirname(HERE);
const QA = join(HERE, "fixtures/qa-bugs/acme-qa");
const QA_OLD = join(HERE, "fixtures/qa-repo/acme-qa"); // BUG-27 and BUG-28 share external_ref JIRA-4411

let failures = 0;
function check(name: string, cond: boolean, detail = ""): void {
  if (cond) console.log(`PASS  ${name}`);
  else {
    failures++;
    console.log(`FAIL  ${name}${detail ? `  — ${detail}` : ""}`);
  }
}
const read = (rel: string): string => readFileSync(join(REPO_ROOT, rel), "utf-8");
const sha = (s: string) => `sha256:${createHash("sha256").update(s).digest("hex")}`;
const api = Intake as any;

/** Every file under a directory with its content hash — to prove nothing was written. */
function snapshot(dir: string): string {
  const out: string[] = [];
  const walk = (d: string) => {
    for (const e of readdirSync(d, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p);
      else out.push(`${p.slice(dir.length)}\0${sha(readFileSync(p, "utf-8"))}`);
    }
  };
  walk(dir);
  return out.join("\n");
}

function cli(args: string[], cwd = REPO_ROOT): any {
  const p = spawnSync(process.execPath, ["--no-warnings", join(HERE, "bug-intake.ts"), ...args], { encoding: "utf-8", cwd });
  try {
    return { code: p.status, json: JSON.parse(p.stdout) };
  } catch {
    return { code: p.status, json: null, raw: p.stdout + p.stderr };
  }
}

const L = (ref: string, root = QA) => api.lookupQaBug?.(root, ref);
const N = (input: Record<string, unknown>) => api.normalizeBug?.(input);
const BEFORE = snapshot(QA);
const BEFORE_OLD = snapshot(QA_OLD);

/* ── 1. QA assigned → ready for Dev ───────────────────────────────────── */
{
  const r = L("BUG-43");
  check("1 assigned bug is ready_for_dev", r?.status === "ready_for_dev" && r.dev_may_start === true, JSON.stringify(r?.status));
  check("1 identity: work_type bug, QA id, origin qa-standalone",
    r?.identity?.work_type === "bug" && r.identity.qa_bug_id === "BUG-43" && r.identity.origin === "qa-standalone");
  check("1 identity: found_in_build is QA's derived value (first reproduction)", r?.identity?.found_in_build === "and-201");
  check("1 identity: affected surfaces", JSON.stringify(r?.identity?.surfaces) === '["android"]');
  check("1 evidence: title, steps, expected, actual, severity",
    r?.evidence?.title === "Checkout total ignores coupon" && r.evidence.steps.length === 3 &&
      r.evidence.expected === "Total shows the 10% discount" && r.evidence.actual === "Total shows the full price" && r.evidence.severity === "major");
  check("1 related QA scopes are carried", JSON.stringify(r?.evidence?.related_scopes) === '["feature:checkout"]');
  check("1 related_feature is the Dev feature QA bound to the related feature scope (dev_handoff)", r?.identity?.related_feature === "checkout-coupons", JSON.stringify(r?.identity?.related_feature));
  check("1 reproduction history is exposed", r?.qa?.reproductions?.length === 1 && r.qa.reproductions[0].outcome === "reproduced");
  check("1 not reopened, so no reopened evidence", r?.reopened === null);
}

/* ── 2. QA reopened → reopened, with the failed cycle's evidence ──────── */
{
  const r = L("qa=BUG-44");
  check("2 reopened bug is reopened and Dev may start the next cycle", r?.status === "reopened" && r.dev_may_start === true, JSON.stringify(r?.status));
  check("2 failed fix build", r?.reopened?.failed_fix_build === "atv-202", JSON.stringify(r?.reopened));
  check("2 failed surfaces", JSON.stringify(r?.reopened?.failed_surfaces) === '["android-tv"]');
  check("2 latest re-test result and notes",
    r?.reopened?.latest_retest?.outcome === "fail" && r.reopened.latest_retest.notes === "Still frozen after resume from Home" && r.reopened.latest_retest.build === "atv-202");
  check("2 re-test evidence", JSON.stringify(r?.reopened?.evidence) === '["videos/BUG-44-atv-202.mp4"]');
  check("2 previous fix claims with outcomes", JSON.stringify(r?.reopened?.previous_fix_claims) === '[{"build":"atv-202","outcome":"failed"}]');
  check("2 no cycle is created at intake", !("cycle" in (r ?? {})) && !("fix_cycle" in (r?.identity ?? {})));
}

/* ── 3–5. QA does not yet, or no longer, hand the bug to Dev ──────────── */
{
  const n = L("BUG-41");
  check("3 new bug needs QA verification; Dev must not start", n?.status === "needs_qa_verification" && n.dev_may_start === false && /verify-bug/.test(n.reason));
  const b = L("BUG-42");
  check("4 verification_blocked needs QA verification; Dev must not start", b?.status === "needs_qa_verification" && b.dev_may_start === false && b.qa.state === "verification_blocked");
  const c = L("BUG-45");
  check("5 closed_verified is closed; Dev must not start", c?.status === "closed" && c.dev_may_start === false && c.qa.state === "closed_verified");
  const f = L("BUG-46");
  check("5 fix_delivered awaits QA re-test; no new fix cycle", f?.status === "awaiting_qa_retest" && f.dev_may_start === false && f.qa.fix_under_test === "and-202");
  for (const r of [n, b, c, f]) check(`3–5 ${r?.identity?.qa_bug_id}: QA ownership is never overridden — the reason names QA's next action`, typeof r?.reason === "string" && r.reason.length > 20);
}

/* ── 6. external_ref on a QA bug; lookups by external ref ─────────────── */
{
  const r = L("BUG-43");
  check("6 a QA bug carries its external_ref", r?.identity?.external_ref === "PAY-1182");
  check("6 its bug_key is still the QA id", r?.identity?.bug_key === "BUG-43");
  check("6 lookup by external ref finds the QA bug", L("external=PAY-1182")?.identity?.qa_bug_id === "BUG-43");
  check("6 qa + external must identify the same bug", L("qa=BUG-43,external=PAY-1182")?.status === "ready_for_dev" && L("qa=BUG-44,external=PAY-1182")?.status === "invalid");
  const amb = L("external=JIRA-4411", QA_OLD);
  check("6 an external ref shared by two QA bugs is ambiguous", amb?.status === "ambiguous" && JSON.stringify(amb.candidates) === '["BUG-27","BUG-28"]', JSON.stringify(amb));
  check("6 an unknown QA bug is invalid, not guessed", L("BUG-99")?.status === "invalid" && L("external=NOPE-1")?.status === "invalid");
}

/* ── 7–10. external, dev-review, dev-testing, production ──────────────── */
const EVIDENCE = { title: "Checkout total ignores coupon", steps: ["Add an item to the cart", "Apply coupon SAVE10", "Open checkout"], expected: "Total shows the 10% discount", actual: "Total shows the full price" };
{
  const e = N({ origin: "external", external_ref: "PAY-1182", ...EVIDENCE, environment: "Pixel 8, staging", surfaces: ["android"] });
  check("7 external-only bug is ready_for_dev without a QA id", e?.status === "ready_for_dev" && e.identity.qa_bug_id === null && e.identity.external_ref === "PAY-1182");
  check("7 environment is carried", e?.evidence?.environment === "Pixel 8, staging");
  for (const origin of ["dev-review", "dev-testing", "production"]) {
    const d = N({ origin, ...EVIDENCE, related_feature: "checkout" });
    check(`${origin === "dev-review" ? 8 : origin === "dev-testing" ? 9 : 10} ${origin} bug is ready_for_dev with a generated DEV key`,
      d?.status === "ready_for_dev" && /^DEV-[0-9a-f]{8}$/.test(d.identity.bug_key) && d.identity.origin === origin, JSON.stringify(d?.identity));
    check(`${origin} bug keeps a given related feature, and needs no QA scope`, d?.identity?.related_feature === "checkout" && d.qa === null);
  }
  check("10 an unknown origin is invalid", N({ origin: "rumour", ...EVIDENCE })?.status === "invalid");
  check("7 an external origin requires an external ref", N({ origin: "external", ...EVIDENCE })?.status === "invalid");
}

/* ── 11–13. deterministic bug_key ─────────────────────────────────────── */
{
  check("11 bug_key from the QA id", L("BUG-44")?.identity?.bug_key === "BUG-44");
  check("12 bug_key from external_ref", N({ origin: "external", external_ref: "PAY-77", ...EVIDENCE })?.identity?.bug_key === "PAY-77");
  const expected = `DEV-${createHash("sha256").update(["production", EVIDENCE.title, EVIDENCE.steps[0]].join("\n")).digest("hex").slice(0, 8)}`;
  const a = N({ origin: "production", ...EVIDENCE });
  const b = N({ origin: "production", ...EVIDENCE, actual: "different actual, same key inputs" });
  check("13 generated DEV key is sha256(origin, title, first step) — first 8 hex", a?.identity?.bug_key === expected, `${a?.identity?.bug_key} vs ${expected}`);
  check("13 it is stable across calls and ignores fields outside the key", a?.identity?.bug_key === b?.identity?.bug_key);
  check("13 a different origin, title or first step gives a different key",
    N({ origin: "dev-review", ...EVIDENCE })?.identity?.bug_key !== expected &&
      N({ origin: "production", ...EVIDENCE, title: "Other" })?.identity?.bug_key !== expected &&
      N({ origin: "production", ...EVIDENCE, steps: ["Other first step", ...EVIDENCE.steps.slice(1)] })?.identity?.bug_key !== expected);
}

/* ── 14–18. evidence fingerprint ──────────────────────────────────────── */
{
  const base = { ...EVIDENCE, surfaces: ["android"], found_in_build: "and-201" };
  const fp = (e: Record<string, unknown>) => api.evidenceFingerprint?.(e);
  check("14 same evidence, same fingerprint", typeof fp(base) === "string" && fp(base) === fp({ ...base }) && /^sha256:[0-9a-f]{64}$/.test(fp(base)));
  check("14 a QA bug and the same evidence entered externally fingerprint identically",
    L("BUG-43")?.bug_evidence_fingerprint === N({ origin: "external", external_ref: "PAY-1182", ...base })?.bug_evidence_fingerprint);
  check("14 surface order does not matter", fp({ ...base, surfaces: ["b", "a"] }) === fp({ ...base, surfaces: ["a", "b"] }));
  check("15 QA state, fix history, re-test history and timestamps never enter the fingerprint",
    fp({ ...base, state: "reopened", fix_claims: [1], retests: [1], at: "2026-10-05T10:00:00Z", severity: "critical", description: "x", external_ref: "Z" }) === fp(base));
  const r44 = L("BUG-44");
  check("15 a reopened QA bug's fingerprint equals that of its bare evidence",
    r44?.bug_evidence_fingerprint === fp({ title: r44?.evidence?.title, steps: r44?.evidence?.steps, expected: r44?.evidence?.expected, actual: r44?.evidence?.actual, surfaces: r44?.identity?.surfaces, found_in_build: r44?.identity?.found_in_build }));
  check("16 steps change it", fp({ ...base, steps: [...EVIDENCE.steps, "Pay"] }) !== fp(base));
  check("16 expected changes it", fp({ ...base, expected: "x" }) !== fp(base));
  check("16 actual changes it", fp({ ...base, actual: "x" }) !== fp(base));
  check("16 title changes it", fp({ ...base, title: "x" }) !== fp(base));
  check("17 a surface change changes it", fp({ ...base, surfaces: ["android", "ios"] }) !== fp(base));
  check("18 found_in_build changes it", fp({ ...base, found_in_build: "and-202" }) !== fp(base) && fp({ ...base, found_in_build: null }) !== fp(base));
}

/* ── 19–20. unsafe identity and missing evidence ──────────────────────── */
{
  for (const bad of ["../etc", "PAY/1", "https://jira.example.com/PAY-1", ".", "..", "a b", "x".repeat(80), ""]) {
    const r = N({ origin: "external", external_ref: bad, ...EVIDENCE });
    check(`19 unsafe external ref ${JSON.stringify(bad.slice(0, 20))} is rejected`, r?.status === "invalid" && /UNSAFE_IDENTITY|MISSING/.test(r.code ?? ""), JSON.stringify(r?.code));
  }
  check("19 an unsafe QA id is rejected before any file is read", L("../../etc")?.status === "invalid" && L("../../etc")?.code === "UNSAFE_IDENTITY");
  for (const missing of ["title", "steps", "expected", "actual"]) {
    const input: Record<string, unknown> = { origin: "production", ...EVIDENCE };
    if (missing === "steps") input.steps = [];
    else delete input[missing];
    const r = N(input);
    check(`20 missing ${missing} is rejected`, r?.status === "invalid" && r.code === "MISSING_EVIDENCE" && r.missing?.includes(missing), JSON.stringify(r));
  }
}

/* ── reopened after more than one failed fix ──────────────────────────── */
{
  // The next cycle starts from the most recent failed fix, never the first one.
  const view = api.parseBugView(readFileSync(join(QA, "bugs/BUG-44/bug.md"), "utf-8"), "BUG-44");
  view.fixClaims.push({ Build: "atv-204", "Claimed at": "2026-10-06T09:00:00.000Z", Outcome: "failed" });
  view.retests.push({ Run: "retest-x", Build: "atv-204", "Fix build": "atv-204", Surface: "android-tv", Device: "Chromecast", Outcome: "fail", At: "2026-10-06T09:30:00.000Z", Notes: "Frozen on cold resume" });
  const runs = [[{ kind: "run.opened", run_id: "retest-x" }, { kind: "result.recorded", case_key: "bug:BUG-44#R1", evidence: ["videos/BUG-44-atv-204.mp4"] }]];
  const r = api.reopenedEvidence(view, runs, "bug:BUG-44");
  check("2 two failed fixes: the latest failed fix build is the one carried", r?.failed_fix_build === "atv-204" && r.latest_retest.notes === "Frozen on cold resume", JSON.stringify(r?.failed_fix_build));
  check("2 two failed fixes: evidence is the latest re-test's, every claim is kept", JSON.stringify(r?.evidence) === '["videos/BUG-44-atv-204.mp4"]' &&
    JSON.stringify(r.previous_fix_claims) === '[{"build":"atv-202","outcome":"failed"},{"build":"atv-204","outcome":"failed"}]');
}

/* ── QA contract and integrity ────────────────────────────────────────── */
{
  const tmp = realpathSync(mkdtempSync(join(tmpdir(), "bug-intake-")));
  const copy = join(tmp, "acme-qa");
  cpSync(QA, copy, { recursive: true });
  // A stale view: the rendered bug.md disagrees with the ledger.
  const md = join(copy, "bugs/BUG-43/bug.md");
  writeFileSync(md, readFileSync(md, "utf-8").replace("Total shows the full price", "Total shows a wrong price"));
  const stale = L("BUG-43", copy);
  check("QA a view that disagrees with the ledger is refused as stale", stale?.status === "invalid" && stale.code === "QA_VIEW_STALE", JSON.stringify(stale?.code));
  cpSync(join(QA, "bugs/BUG-43/bug.md"), md);
  // A view missing a re-test the ledger records is stale too.
  const md44 = join(copy, "bugs/BUG-44/bug.md");
  writeFileSync(md44, readFileSync(md44, "utf-8").replace(/\| retest-[^\n]*\n/, ""));
  check("QA a view missing a re-test the ledger records is stale", L("BUG-44", copy)?.code === "QA_VIEW_STALE", JSON.stringify(L("BUG-44", copy)?.code));
  cpSync(join(QA, "bugs/BUG-44/bug.md"), md44);
  // A hand-edited ledger record no longer verifies.
  const stream = join(copy, "qa-ledger/scopes/bug/BUG-43.jsonl");
  writeFileSync(stream, readFileSync(stream, "utf-8").replace('"Total shows the full price"', '"Total shows nothing"'));
  check("QA a hand-edited ledger record is unverifiable", L("BUG-43", copy)?.code === "QA_LEDGER_UNVERIFIABLE");
  cpSync(join(QA, "qa-ledger/scopes/bug/BUG-43.jsonl"), stream);
  // A view whose shape is not the contracted one is refused, never guessed at.
  writeFileSync(md, readFileSync(md, "utf-8").replace("## Re-test History", "## Retests"));
  check("QA a view not in the contracted shape is refused", L("BUG-43", copy)?.code === "QA_VIEW_CONTRACT");
  cpSync(join(QA, "bugs/BUG-43/bug.md"), md);
  // Sections in another order are not the contracted shape either.
  writeFileSync(md, readFileSync(md, "utf-8").replace("## Devices", "## @@").replace("## Linked Test Cases", "## Devices").replace("## @@", "## Linked Test Cases"));
  check("QA a view with its sections reordered is refused", L("BUG-43", copy)?.code === "QA_VIEW_CONTRACT");
  cpSync(join(QA, "bugs/BUG-43/bug.md"), md);
  // A related feature scope with no recorded Dev handoff yields no Dev feature — none is invented.
  const feature = join(copy, "qa-ledger/scopes/feature/checkout.jsonl");
  writeFileSync(feature, readFileSync(feature, "utf-8").split("\n")[0] + "\n");
  const unbound = L("BUG-43", copy);
  check("QA without a recorded dev_handoff, related_feature is null", unbound?.status === "ready_for_dev" && unbound.identity.related_feature === null, JSON.stringify(unbound?.identity?.related_feature));
  cpSync(join(QA, "qa-ledger/scopes/feature/checkout.jsonl"), feature);
  check("QA a missing view is refused with the regeneration hint", (rmSync(md), L("BUG-43", copy))?.code === "QA_VIEW_MISSING");
  check("QA a path that is not a QA repository is refused", L("BUG-43", tmp)?.code === "NOT_A_QA_REPO");
  rmSync(tmp, { recursive: true, force: true });

  const contract = read("docs/qa-bug-view-contract.md");
  check("QA the consumer contract exists and names both sources", /qa-ledger\/scopes\/bug/.test(contract) && /bugs\/<id>\/bug\.md/.test(contract));
  check("QA the contract pins the QA renderer it was written against", /renderBugMarkdown/.test(contract) && /8d8ed99/.test(contract));
  check("QA the contract states the limitation of reading a derived view", /limitation/i.test(contract));
  const PIN = "sha256:2493543026a34cec95927baffa02f2d083be736fd1ca8e89f811b80284728488";
  check("QA the contract copy is pinned", sha(contract) === PIN, sha(contract));
}

/* ── CLI ──────────────────────────────────────────────────────────────── */
{
  const a = cli(["lookup", "BUG-44", "--qa-repo", QA]);
  check("CLI lookup prints one JSON object and exits 0", a.code === 0 && a.json?.status === "reopened");
  const v = cli(["validate", "BUG-43", "--qa-repo", QA]);
  check("CLI validate reports the contract and integrity verdict", v.code === 0 && v.json?.status === "valid", JSON.stringify(v.json));
  const n = cli(["normalize", "--origin", "external", "--external", "PAY-1182", "--title", EVIDENCE.title, "--step", EVIDENCE.steps[0], "--step", EVIDENCE.steps[1], "--step", EVIDENCE.steps[2],
    "--expected", EVIDENCE.expected, "--actual", EVIDENCE.actual, "--surfaces", "android", "--found-in-build", "and-201"]);
  check("CLI normalize from flags matches the QA bug's fingerprint", n.json?.bug_evidence_fingerprint === L("BUG-43")?.bug_evidence_fingerprint, JSON.stringify(n.json?.status));
  const tmp = realpathSync(mkdtempSync(join(tmpdir(), "bug-intake-report-")));
  writeFileSync(join(tmp, "report.json"), JSON.stringify({ title: EVIDENCE.title, steps: EVIDENCE.steps, expected: EVIDENCE.expected, actual: EVIDENCE.actual, environment: "prod, v2.4.0" }));
  const rep = cli(["normalize", "--origin", "production", "--report", join(tmp, "report.json")], tmp);
  check("CLI normalize from a report file works", rep.json?.status === "ready_for_dev" && rep.json.evidence.environment === "prod, v2.4.0");
  check("24 no planning artifact or any file is generated", readdirSync(tmp).join(",") === "report.json");
  const bad = cli(["frobnicate"]);
  check("CLI an unknown command is a JSON refusal, still exit 0", bad.code === 0 && bad.json?.status === "invalid");
  rmSync(tmp, { recursive: true, force: true });
}

/* ── 21–25. read-only, no Project Knowledge, no QA writes, no planning ── */
{
  check("21 the QA fixture repository is byte-identical after every lookup", snapshot(QA) === BEFORE && snapshot(QA_OLD) === BEFORE_OLD);
  const src = read("scripts/bug-intake.ts").replace(/\/\*\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
  check("21 the helper uses no write API", !/\b(writeFile|appendFile|mkdir|rmSync|rm\(|unlink|rename|copyFile|cpSync|createWriteStream|truncate)/.test(src));
  check("22 the helper never touches Project Knowledge", !/repo-knowledge|\.ono\b|read-repo-knowledge|knowledge lookup/.test(src));
  check("23 the helper never runs the QA helper or any process", !/qa-ledger\.mjs|child_process|spawn|exec(File)?Sync/.test(src));
  check("24 the helper writes no planning artifact path", !/docs\/bugs|bug-work-plan|task-state\.ts|docs\/tasks/.test(src));
  check("the helper reads no clock and no randomness", !/\bnew Date\b|Date\.now|Math\.random|randomUUID/.test(src));
  check("25 the suite is registered with the check harness", /"bug-intake"/.test(read("scripts/check.ts")));
  for (const rel of ["commands/analyze-feature.md", "commands/implement-task.md", "commands/create-dev-qa-notes.md", "commands/review-code.md", "commands/prepare-mobile-release.md", "scripts/task-state.ts", "scripts/read-repo-knowledge.ts"]) {
    check(`25 ${rel} does not reference bug intake (Step 1 changes nothing downstream)`, !/bug-intake/.test(read(rel)));
  }
}

if (failures > 0) {
  console.log(`\n${failures} failure(s)`);
  process.exit(1);
}
console.log("\nall bug-intake checks passed");
